# Site settings
title: Gordon Cheng
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Gordon Cheng
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gcky.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins: [jekyll-paginate-v2]
